<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Clang_Format_Gui</AssemblyName>
    <RootNamespace>Clang_Format_Gui</RootNamespace>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Main_Form.Designer.cs">
      <DependentUpon>Main_Form.cs</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
